name: taekwon
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  device_preview: ^1.3.1
  table_calendar: ^3.0.9
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.4
  intl: ^0.20.2
  cloud_firestore: ^4.17.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true